title: NYPL DigPres Docs
description: >-
  Documentation for the New York Public Library's
  digital preservation workflows, practices, and policies
  for its collections.
baseurl: "/digpres-docs" # the subpath of your site, e.g. /blog
url: "https://nypl.github.io"

remote_theme: pmarsceill/just-the-docs

search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true